// Common tag suggestions for licitaciones
export const COMMON_TAGS = [
    'Urgente',
    'Tecnología',
    'Servicios',
    'Obra',
    'Suministro',
    'Consultoría',
    'Mantenimiento',
    'Cloud',
    'Ciberseguridad',
    'IA',
    'Big Data',
    'Desarrollo Software',
    'Infraestructura',
    'Formación',
    'Soporte',
    'Alta Prioridad',
    'Multianual',
    'Lote Único',
    'Framework',
    'Público',
    'Privado',
];
